Testing To Do List: part 2
WilhelmK109/testing-to-do-list pull request #2
Opened 2023-03-03 20:01 UTC by WilhelmK109

### In this project, I did the following:
- Wrote test code to test functions responsible for the status and content updates.

![Screenshot (83)](https://user-images.githubusercontent.com/74548443/222815266-f0bb0d74-1b35-4f73-ba72-93f91c21f296.png)

2023-03-03 20:05 UTC, Gambit142 reviewed
Hi @WilhelmK109 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the Eslint linters checks failed to pass. Kindly fix this issue 👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-03 20:36 UTC, Gambit142 requested changes
Hi @WilhelmK109 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Wrote tests for the function that edits task ✔️ 
- Wrote tests for the function that deletes all completed tasks ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-03 20:36 UTC, Gambit142 commented on src/tests/editTask.test.js
> +});
- [ ] Great work writing these tests. Impressive work done 👏 To make your work complete, kindly write tests for the function that is responsible for changing the _**completed**_ status of a task. This means you should write tests for the function that changes a task's completed status from `true` to `false` and vice versa.

2023-03-04 06:06 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @WilhelmK109    👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔  Made required changes👍 
✔ All tests are passing👍 
✔ no linter errors 👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 06:10 UTC, merged